#Base dir of project
basedir: /export/web/ant_hill

#AntHillExtension libriries
lib_path: spec/support/ant_hill_libs.rb

# Time to sleep before next request of ant
sleep_interval: 1

log_dir: /tmp/ant_hill
log_level: 

types:
  first:
    ant_colony_class: AntHill::FirstAntColony
    creep_modifier_class: AntHill::FirstCreepModifier

  second:
    ant_colony_class: AntHill::SecondAntColony
    creep_modifier_class: AntHill::SecondCreepModifier

default_type: first


#Test nodes

creeps:
  -
    name: one
    host: ivan.test.com
    login: test
  -
    name: two
    host: sel01.test.com
    login: test
  -
    name: three
    host: sel02.test.com
    login: test
  -
    name: four
    host: sel03.test.com
    login: test
